// <auto-generated />
namespace Bibliotek.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TilføjetAnnotationsfortablenames : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TilføjetAnnotationsfortablenames));
        
        string IMigrationMetadata.Id
        {
            get { return "201804170818562_Tilføjet Annotations for table names"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
